// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYDVleoz64qXRGkQCQDvW1Xdi_jM1PIhs',
    appId: '1:164134187996:android:50c9e742710ec5c6199519',
    messagingSenderId: '164134187996',
    projectId: 'barbers-mk',
    storageBucket: 'barbers-mk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8hH-HXtHBgHiXVyNTIdECAso0G1ySWUM',
    appId: '1:164134187996:ios:52531bf451dee865199519',
    messagingSenderId: '164134187996',
    projectId: 'barbers-mk',
    storageBucket: 'barbers-mk.firebasestorage.app',
    iosBundleId: 'com.example.barberMk',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2L2SJaMG9NdidJGueWhbQ8daA8YQlQ4w',
    appId: '1:164134187996:web:b8300a2c3e23a3b0199519',
    messagingSenderId: '164134187996',
    projectId: 'barbers-mk',
    authDomain: 'barbers-mk.firebaseapp.com',
    storageBucket: 'barbers-mk.firebasestorage.app',
    measurementId: 'G-62NMXGLMCW',
  );

}